sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - npm i -g npx
script:
  - npm test
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
      git checkout ${TRAVIS_BRANCH};
      git reset --hard ${TRAVIS_COMMIT};
      git remote set-url origin ${CIVAR_GH_REPOSITORY_URL};
      printf -- "//registry.npmjs.org/:_authToken=${CIVAR_NPM_TOKEN}" > ./.npmrc;
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        COMMIT_MESSAGE="${TRAVIS_COMMIT_MESSAGE}";
        if [ -z "${COMMIT_MESSAGE##*"[major release]"*}" ]; then
          zsc version bump --major;
        elif [ -z "${COMMIT_MESSAGE##*"[minor release]"*}" ]; then
          zsc version bump --minor;
        else
          zsc version bump --patch;
        fi;
        git push --tags;
        zsc publish npm --auto;
      fi;
    fi;
